### PR TITLE
Add configuration property for allowed length of LNURL-pay comments

### PR DESCRIPTION
**Pull request by yanascz**

### CODE REVIEW

**Comment by bumi** [comment]
thanks for the PR! that looks good! 

do you know why not more lnurlp implementations add support for comments like that?

**Comment by yanascz** [comment]
> do you know why not more lnurlp implementations add support for comments like that?

Maybe because it’s defined under different RFC? I can only guess. I saw support for comments by ln.tips so I started digging and discovered #12.

**Comment by ok300** [comment]
Why wait when I can run your branch directly :)

Started doing that, works great.

Just one question, why is `lnurlp-comment-allowed` default 0? I doubt people don't want comments by default, I'd say a reasonable number (200-500) is a good sane default. Enough for comment, but small enough to not run into any limits.

**Comment by yanascz** [comment]
> Just one question, why is `lnurlp-comment-allowed` default 0? I doubt people don't want comments by default, I'd say a reasonable number (200-500) is a good sane default. Enough for comment, but small enough to not run into any limits.

I wanted the change to be backwards compatible. But I'm OK with a different default, e.g. 210 (as 21 is such a nice number 😉). Ultimately, it's up to @bumi to decide what default he wants.

**Comment by bumi** [comment]
ok, cool. then let's enable it by default. @yanascz can you update that, then I'll merge it and make a new release
@ok300 thanks for testing and giving feedback.

**Comment by yanascz** [comment]
> ok, cool. then let's enable it by default. @yanascz can you update that, then I'll merge it and make a new release

Done! ✅

**Pull request merged**
